@startuml

skinparam monochrome true

actor システム
database 緯度経度一覧テーブル as DB
database 移動時間一覧テーブル as DB2
participant GoogleDirectionApi

システム -> DB : 出発地、目的地取得
DB -> GoogleDirectionApi : 移動時間取得
DB -> DB2 : なければ移動時間を返す

@enduml