@startuml

actor システム 

boundary AWSサーバー

control 目的地の一覧取得
control 旅行プランを生成する

entity 目的地一覧
entity 旅行プラン一覧

システム -> AWSサーバー : アクセス
AWSサーバー -> 目的地の一覧取得 : 呼び出し
目的地の一覧取得 -> 目的地一覧 : 問い合わせ
目的地の一覧取得 -> 旅行プランを生成する : 呼び出し
旅行プランを生成する -> 旅行プラン一覧 : 出力

@enduml
