@startuml

actor ユーザー

boundary 出発地決定画面
boundary 住所入力画面
boundary アラートを表示

control 出発地の決定

entity 出発地

ユーザー -> 出発地決定画面
出発地決定画面 -> 住所入力画面 : 住所で決めるを押下
住所入力画面 -> 出発地の決定 : 決定を押下
出発地の決定 -> アラートを表示 : 住所が入力されていない場合
アラートを表示 -> 住所入力画面
出発地の決定 -> 出発地 : 出力

@enduml