@startuml

actor ユーザー

boundary ホーム画面
boundary アラートを表示
boundary 旅行プラン表示画面
boundary 旅行プラン詳細表示画面
boundary 移動経路表示画面

control 移動経路を取得

entity 移動経路情報

ユーザー -> 旅行プラン表示画面
ユーザー -> 旅行プラン詳細表示画面

旅行プラン表示画面 -> 移動経路を取得 : 移動経路を押下
旅行プラン詳細表示画面 -> 移動経路を取得 : 移動経路を押下
移動経路を取得 -> 移動経路情報 : 出力
移動経路を取得 -> アラートを表示 : 移動経路を取得ができなかった場合
アラートを表示 -> ホーム画面 : OKを押下
ホーム画面 -> ユーザー
移動経路を取得 -> 移動経路表示画面 : 表示
移動経路表示画面 -> ユーザー

@enduml