@startuml

actor ユーザー

boundary ホーム画面
boundary アラートを表示
boundary 旅行プラン表示画面
boundary 旅行プラン詳細表示画面
boundary 目的地詳細情報表示画面

control 目的地詳細情報を取得

entity 目的地詳細情報

ユーザー -> 旅行プラン表示画面
ユーザー -> 旅行プラン詳細表示画面

旅行プラン表示画面 -> 目的地詳細情報を取得 : インフォメーションを押下
旅行プラン詳細表示画面 -> 目的地詳細情報を取得 : インフォメーションを押下
目的地詳細情報を取得 -> 目的地詳細情報 : 出力
目的地詳細情報を取得 -> アラートを表示 : 目的地詳細情報を取得ができなかった場合
アラートを表示 -> ホーム画面 : OKを押下
ホーム画面 -> ユーザー
目的地詳細情報を取得 -> 目的地詳細情報表示画面 : 表示
目的地詳細情報表示画面 -> ユーザー

@enduml