@startuml

actor ユーザー

boundary ホーム画面
boundary アラートを表示
boundary 目的決定方法選択画面
boundary 旅行診断ツール画面

control 旅行診断ツールの質問を取得
control 旅行診断

entity 目的

ユーザー -> 目的決定方法選択画面
目的決定方法選択画面 -> 旅行診断ツールの質問を取得 : 旅行診断ツールで決定するを押下
旅行診断ツールの質問を取得 -> 旅行診断ツール画面 : 表示
旅行診断ツール画面 -> 旅行診断 : 旅行診断ツールのすべての質問に回答する
旅行診断ツールの質問を取得 -> アラートを表示 : 旅行診断ツールの質問を取得ができなかった場合
アラートを表示 -> ホーム画面 : OKを押下
ホーム画面 -> ユーザー
旅行診断 -> 目的 : 出力

@enduml