@startuml

actor ユーザー

boundary 出発地決定画面
boundary GPS取得画面

control GPSで現在地を取得
control 出発地の決定
control 現在地を再取得
control 穴吹コンピュータカレッジの位置情報を現在地に設定 as 固定位置情報取得

entity 出発地

ユーザー -> 出発地決定画面
出発地決定画面 -> GPSで現在地を取得 : GPSで決めるを押下
GPSで現在地を取得 -> 固定位置情報取得 : GPSで現在地を取得できなかった場合
固定位置情報取得 ->  GPS取得画面 : 表示
GPSで現在地を取得 -> GPS取得画面 : 表示
GPS取得画面 -> 出発地の決定 : 決定を押下
GPS取得画面 -> GPSで現在地を取得 : もう一度取得を押下
出発地の決定 -> 出発地 : 出力

@enduml