@startuml

actor ユーザー

boundary ホーム画面
boundary アラートを表示
boundary 旅行プラン表示画面
boundary 旅行プラン一覧表示画面
boundary 旅行プラン詳細表示画面

control 旅行プランの詳細を取得

ユーザー -> 旅行プラン表示画面
ユーザー -> 旅行プラン一覧表示画面
旅行プラン表示画面 -> 旅行プランの詳細を取得 : 保存を押下
旅行プラン一覧表示画面 -> 旅行プランの詳細を取得 : プランを選択
旅行プランの詳細を取得 -> 旅行プラン詳細表示画面 : 表示
旅行プランの詳細を取得 -> アラートを表示 : 旅行プランの詳細を取得ができなかった場合
アラートを表示 -> ホーム画面 : OKを押下
ホーム画面 -> ユーザー
旅行プラン詳細表示画面 -> ユーザー

@enduml