@startuml

usecase 駅名で出発地を決める

actor ユーザー

boundary ホーム画面
boundary アラートを表示
boundary 出発地決定画面
boundary 駅選択画面

control 全国の路線や駅名情報の取得
control 出発地の決定

entity 出発地

ユーザー --> 出発地決定画面
出発地決定画面 --> 全国の路線や駅名情報の取得 : 駅で決めるを押下
全国の路線や駅名情報の取得 --> 駅選択画面 : 表示
全国の路線や駅名情報の取得 --> アラートを表示 : 全国の路線や駅名情報の取得ができなかった場合
アラートを表示 --> ホーム画面 : OKを押下
ホーム画面 --> ユーザー
駅選択画面 --> 出発地の決定 : 駅を選択し、決定を押下
出発地の決定 --> 出発地 : 出力

@enduml