@startuml

usecase 旅行プランの再取得をする

actor ユーザー

boundary ホーム画面
boundary アラートを表示
boundary 旅行プラン表示画面

control 出発地と目的をもとに旅行プランの取得

entity 旅行プラン

ユーザー --> 旅行プラン表示画面
出発地と目的をもとに旅行プランの取得 -- 旅行プラン : 出力
出発地と目的をもとに旅行プランの取得 --> 旅行プラン表示画面 : 表示
出発地と目的をもとに旅行プランの取得 --> アラートを表示 : 旅行プランの取得ができなかった場合
アラートを表示 --> ホーム画面 : OKを押下
ホーム画面 --> ユーザー
旅行プラン表示画面 --> 出発地と目的をもとに旅行プランの取得 : 再生成を押下

@enduml