@startuml

usecase 旅行プランの目的地の入れ替えをする

actor ユーザー

boundary 旅行プラン詳細表示画面
boundary 旅行プラン編集画面

control 目的地の入れ替え
control 旅行プランの保存

entity 旅行プラン

ユーザー --> 旅行プラン詳細表示画面
旅行プラン詳細表示画面 --> 旅行プラン編集画面 : 編集を押下
旅行プラン編集画面 --> 目的地の入れ替え : 対象の目的地を入れ替える
目的地の入れ替え --> 旅行プランの保存 : 完了を押下
目的地の入れ替え --> 旅行プラン詳細表示画面 : キャンセルを押下
旅行プランの保存 --> 旅行プラン詳細表示画面
目的地の入れ替え -- 旅行プラン : 更新

@enduml