@startuml

skinparam classAttributeIconSize 0

    class 移動経路{
        - プラン:object
        + 移動経路取得():void
        + 移動経路表示():void
    }

    class googlemap{
        + 移動経路取得():void
    }

    移動経路 .-- googlemap
    
    class 画面遷移{
        + ページ遷移先の取得:String
        + ページ遷移先の設定:void
    }
    
@enduml