@startuml

skinparam classAttributeIconSize 0

package DB <<Database>>  {
    left to right direction

    class 質問{
        # テーブル名
        + 全権取得():array
    }
}

package コントローラ{
    class 質問操作 {
        + 質問一覧の取得():array
    }

    .質問 -- .質問操作
}

@enduml