@startuml

skinparam classAttributeIconSize 0

    class プラン生成{
        - 出発地緯度経度:String
        - 目的:String
        - メイン目的:String
        - サブ目的:String
        - プラン:object
        + プラン取得():void
        + プラン表示():void
    }

    class ajax{
        + ajax通信を行う(ajax通信をするURL:String,成功時に返すメソッドの区分:String,自作APIか外部APIかのフラグ:String,データタイプ:String):object
        + プラン取得():void
    }

    プラン生成 .-- ajax
    
    class 画面遷移{
        + ページ遷移先の取得:String
        + ページ遷移先の設定:void
    }
    
@enduml