@startuml

skinparam classAttributeIconSize 0

    class GPS{
        + 位置情報を取得:object
        + YahooMapの出力:void
    }

    class yahooMap{
        + YahooMapの出力(緯度:String,経度:String):object
    }
    
    GPS .-- yahooMap

    class 画面遷移{
        + ページ遷移先の取得:String
        + ページ遷移先の設定:void
    }
    
@enduml