@startuml

skinparam classAttributeIconSize 0

package DB <<Database>>  {
    left to right direction

    class 質問ポイント{
        # テーブル名
        + 質問の回答結果によっておすすめの目的を上位３件を取得(回答結果:array):array
    }
}

package コントローラ{
    class 質問操作 {
        + おすすめの目的を取得(回答結果:array):array
    }

    .質問ポイント -- .質問操作
}

@enduml